#!/usr/bin/env bash
# Install coderef git hooks into the current (or specified) git repo.
#
# Usage:
#   ./install.sh              # install into cwd's git repo
#   ./install.sh /path/to/repo

set -euo pipefail

CODEREF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$(pwd)}"

REPO_ROOT="$(git -C "$TARGET_DIR" rev-parse --show-toplevel 2>/dev/null)" || {
    echo "error: '$TARGET_DIR' is not inside a git repository" >&2
    exit 1
}

HOOKS_DIR="$REPO_ROOT/.git/hooks"

# ── Install pre-commit ────────────────────────────────────────────────────────

HOOK_SRC="$CODEREF_DIR/hooks/pre-commit"
HOOK_DST="$HOOKS_DIR/pre-commit"

if [[ -f "$HOOK_DST" ]]; then
    # Check if coderef is already the installed hook
    if grep -q "coderef" "$HOOK_DST" 2>/dev/null; then
        echo "coderef: pre-commit hook already installed — skipping"
    else
        # Chain: preserve existing hook, install coderef alongside it
        echo "coderef: existing pre-commit hook found — creating chain"
        cp "$HOOK_DST" "$HOOKS_DIR/pre-commit.orig"
        echo "coderef: backed up existing hook to pre-commit.orig"

        cp "$HOOK_SRC" "$HOOKS_DIR/pre-commit.coderef"
        chmod +x "$HOOKS_DIR/pre-commit.coderef"

        cat > "$HOOK_DST" <<'CHAIN'
#!/usr/bin/env bash
# Generated by coderef install — runs original hook then coderef
set -e
HOOKS_DIR="$(dirname "$0")"
if [[ -x "$HOOKS_DIR/pre-commit.orig" ]]; then
    "$HOOKS_DIR/pre-commit.orig"
fi
exec python3 "$HOOKS_DIR/pre-commit.coderef"
CHAIN
        chmod +x "$HOOK_DST"
        echo "coderef: chain hook installed at $HOOK_DST"
    fi
else
    cp "$HOOK_SRC" "$HOOK_DST"
    chmod +x "$HOOK_DST"
    echo "coderef: pre-commit hook installed at $HOOK_DST"
fi

# ── Install post-checkout ─────────────────────────────────────────────────────

for hook in post-checkout post-merge; do
    SRC="$CODEREF_DIR/hooks/$hook"
    DST="$HOOKS_DIR/$hook"

    if [[ -f "$DST" ]]; then
        if grep -q "coderef" "$DST" 2>/dev/null; then
            echo "coderef: $hook hook already installed — skipping"
        else
            # Chain
            cp "$DST" "$HOOKS_DIR/$hook.orig"
            cat > "$DST" <<CHAIN
#!/usr/bin/env bash
# Generated by coderef install — runs original hook then coderef
set -e
HOOKS_DIR="\$(dirname "\$0")"
if [[ -x "\$HOOKS_DIR/$hook.orig" ]]; then
    "\$HOOKS_DIR/$hook.orig" "\$@"
fi
exec bash "\$HOOKS_DIR/$hook.coderef" "\$@"
CHAIN
            chmod +x "$DST"
            cp "$SRC" "$HOOKS_DIR/$hook.coderef"
            chmod +x "$HOOKS_DIR/$hook.coderef"
            echo "coderef: $hook chain hook installed"
        fi
    else
        cp "$SRC" "$DST"
        chmod +x "$DST"
        echo "coderef: $hook hook installed at $DST"
    fi
done

# ── Create .coderef if missing ───────────────────────────────────────────────────

REFS_FILE="$REPO_ROOT/.coderef"
if [[ ! -f "$REFS_FILE" ]]; then
    touch "$REFS_FILE"
    echo "coderef: created empty .coderef at $REFS_FILE"
fi

echo "coderef: installation complete"
